dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk9
install: true
script: mvn -B -Papache-release -Dgpg.skip=true verify
jobs:
  include:
    - if: repo = "apache/axis2-java" AND branch = trunk AND type = push
      stage: deploy
      script: mvn -B -s .travis-settings.xml -Papache-release -Dgpg.skip=true -DskipTests=true deploy
env:
  global:
    - secure: "IzpkWYL9tH5bE6I6nDbgW6HUlz/+R7XuBXo5997r2adRz8Q1vnSA4gvvMDLyvNjUXDWB99HNLXMaInYlpLNOjBjgXx0abmbcUBfCu0/923iuT80IowT7kNcQK+k4b9ajFT4EZAWySru1SyeTa1VgEjCnAhynDXhhGwCjjakxGrY="
    - secure: "iAPTcu1L6InO4F39F22iDccXhc59H7vVbEXZF3IxeWdf0RbtaahWrxHO532ILmTxN+wMio0GMNtmbyp8GP1Q30g7ZtK0YINeKcvR/PesiIcerm5Zp7Bh1a2PB3wJFnlykYBenn+AXXXZKRrmPki2aXFC0wEQ6hgKBQfVgwOcvHA="
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    # java-dev@axis.apache.org doesn't work here because it's not an address registered on GitHub.
    - veithen@apache.org
