# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
  BASE_JAVA_VERSION: 17
  DEFAULT_JAVA_DISTRIBUTION: 'temurin'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 25 ]
    name: "Java ${{ matrix.java }}"
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-java-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-java-${{ matrix.java }}-
          maven-
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ env.DEFAULT_JAVA_DISTRIBUTION }}
    - name: Build
      run: mvn -B -e -Papache-release -Dgpg.skip=true -Dmaven.compiler.release=${{ matrix.java }} verify
    - name: Remove Snapshots
      run: find ~/.m2/repository -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1.0.26
      with:
        github-report: true
        report-path: '**/target/surefire-reports/*.xml'
        integrations-config: |
          {
            "junit-to-ctrf": {
              "enabled": true,
              "action": "convert",
              "options": {
                "output": "./target/ctrf-reports/ctrf-report.json",
                "toolname": "junit-to-ctrf",
                "useSuiteName": false,
                "env": {
                  "appName": "axis2"
                }
              }
            }
          }
      if: always()
  site:
    name: Site
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-site-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-site-
          maven-
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.BASE_JAVA_VERSION }}
        distribution: ${{ env.DEFAULT_JAVA_DISTRIBUTION }}
    - name: Build
      run: mvn -B -e -Dmaven.test.skip=true -Dmaven.compiler.release=${{ env.BASE_JAVA_VERSION }} package site-deploy
    - name: Remove Snapshots
      run: find ~/.m2/repository -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'apache/axis-axis2-java-core'
    name: Deploy
    runs-on: ubuntu-24.04
    needs:
      - build
      - site
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Cache Maven Repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-deploy-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-deploy-
          maven-
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.BASE_JAVA_VERSION }}
        distribution: ${{ env.DEFAULT_JAVA_DISTRIBUTION }}
        server-id: apache.snapshots.https
        server-username: NEXUS_USER
        server-password: NEXUS_PW
    - name: Deploy
      run: mvn -B -e -Papache-release -Dgpg.skip=true -Dmaven.test.skip=true -Dmaven.compiler.release=${{ env.BASE_JAVA_VERSION }} deploy
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
    - name: Remove Snapshots
      run: find ~/.m2/repository -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf
